package ventanas;

import clases.Prestamo;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Minor
 */
public class Listado_Prestamos extends javax.swing.JFrame {

    // variables que se utilizaran por toda la clase
    String LineaMostrar = "";
    ArrayList<String> listaPrestamos = new ArrayList<String>();

  
    public Listado_Prestamos() {
        initComponents();
        
        //para darle nombre a la ventana y centrarla
        this.setTitle("Proyecto Final Minor Marin Obando");
        this.setLocationRelativeTo(null);
        //para darle color al panel
        Panel_Listado.setBackground(new Color(253, 255, 228, 140));
        this.Panel_Listado.setBackground(new Color(246, 235, 241, 140));
        this.Panel_Titulo.setBackground(new Color(246, 235, 241, 140));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Titulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Panel_Listado = new javax.swing.JPanel();
        ID_jtextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Buscar = new javax.swing.JButton();
        Box_Tipo_Prestamo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Titulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Listado de Prestamos ");

        javax.swing.GroupLayout Panel_TituloLayout = new javax.swing.GroupLayout(Panel_Titulo);
        Panel_Titulo.setLayout(Panel_TituloLayout);
        Panel_TituloLayout.setHorizontalGroup(
            Panel_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_TituloLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel1)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        Panel_TituloLayout.setVerticalGroup(
            Panel_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_TituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        getContentPane().add(Panel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        Panel_Listado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ID_jtextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ID_jtextFieldKeyTyped(evt);
            }
        });

        jLabel2.setText("Buscar por Cedula");

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        Box_Tipo_Prestamo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "personal", "pymes", "vivienda" }));

        jLabel3.setText("Buscar por Tipo Prestamo");

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificación", "Nombre", "Primer Apellido", "Segundo Apellido", "Tipo Préstamo", "Cuota Mensual"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Tabla);

        jButton1.setText("Menu Principal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_ListadoLayout = new javax.swing.GroupLayout(Panel_Listado);
        Panel_Listado.setLayout(Panel_ListadoLayout);
        Panel_ListadoLayout.setHorizontalGroup(
            Panel_ListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ListadoLayout.createSequentialGroup()
                .addGroup(Panel_ListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_ListadoLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(Panel_ListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Panel_ListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ID_jtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Box_Tipo_Prestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(87, 87, 87)
                        .addComponent(Buscar))
                    .addGroup(Panel_ListadoLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_ListadoLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jButton1)
                        .addGap(156, 156, 156)
                        .addComponent(jButton2)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        Panel_ListadoLayout.setVerticalGroup(
            Panel_ListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_ListadoLayout.createSequentialGroup()
                .addGroup(Panel_ListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_ListadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Panel_ListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ID_jtextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Panel_ListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Box_Tipo_Prestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(Panel_ListadoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(Buscar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(Panel_ListadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(35, 35, 35))
        );

        getContentPane().add(Panel_Listado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 710, 350));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Listado.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Boton para buscar por ID o por Tipo de Prestamo
    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
      //se crea una tabla con el modelo de la del arraylist que se creó arriba 
        DefaultTableModel m1 = (DefaultTableModel) Tabla.getModel();
        // se crea un objeto de la clase file el cual representa un archivo.
        File file = new File("prestamos_aprobados.txt");
        String Tipo_Prestamo = "";

        if (file.exists()){
        try {
            // si el ID está vacío y no ha seleccionado nada en el combo box despliega un mensaje y se limpia la tabla 
            if (ID_jtextField.getText().trim().equals("") && Box_Tipo_Prestamo.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, " Debe Ingresar una Identificacion o Selecionar un Tipo de Préstamo ", "ERROR", JOptionPane.ERROR_MESSAGE);
                //reiniciar la tabla     
                m1.setRowCount(0);
                return;
            }

            // si el ID está vacío entra en el if
            if (ID_jtextField.getText().trim().equals("")) {
                 // con el switch se determina que tipo de préstamo se seleccionó a buscar
                switch (Box_Tipo_Prestamo.getSelectedIndex()) {
                    case 1:
                        Tipo_Prestamo = "Personal";
                        break;
                    case 2:
                        Tipo_Prestamo = "Pymes";
                        break;
                    case 3:
                        Tipo_Prestamo = "Vivienda";
                        break;
                }

            }
            //reiniciar la tabla
            m1.setRowCount(0);

            // se crea un objeto para leer el archivo de los datos de los préstamos en modo lectura
            BufferedReader Arch_Prestamos = new BufferedReader(new FileReader(file));
            String linea;
            LineaMostrar = "";
            // se recorre el archivo linea a linea 
            while ((linea = Arch_Prestamos.readLine()) != null) {

                // si la línea contiene el ID y el combo box es 0 entonces es porque está buscando la información 
                //únicamente por cédula

                if ((linea.contains(ID_jtextField.getText())) && Box_Tipo_Prestamo.getSelectedIndex() == 0) {
                //se agrega a la tabla la información de la línea con la cedula encontrada
                    LineaMostrar = linea;
                    m1.addRow(LineaMostrar.split("/"));

                }
              // si la línea contiene el tipo de préstamo seleccionado en el combo box, y la cedula esta en blanco 
                //es porque esta buscando por tipo de préstamo

                if (linea.contains(Tipo_Prestamo) && ID_jtextField.getText().trim().equals("")) {
                   // si encuentra lineas con el tipo de préstamo seleccionado se agregan a la tabla
                    LineaMostrar = linea;
                    m1.addRow(LineaMostrar.split("/"));

                }
                 

            }
            Arch_Prestamos.close();// se cierra el archivo 
            
            //Si el JtextField del ID no está vacío y el combo box es diferente de 0 muestra un mensaje
            //que indica que solo se pueden buscar por cedula o por tipo de préstamo pero no ambos a la vez

            if (!ID_jtextField.getText().trim().equals("")&&Box_Tipo_Prestamo.getSelectedIndex()!=0) {
                ID_jtextField.setText("");
                Box_Tipo_Prestamo.setSelectedIndex(0);
                JOptionPane.showMessageDialog(null, " Solo puede buscar por Cedula o por Tipo de Prestamo ", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, " Archivo No Encontrado ", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        }else {
           JOptionPane.showMessageDialog(null, " Aun no hay Clientes con Prestamos ", "ERROR", JOptionPane.ERROR_MESSAGE);  
        }
        


    }//GEN-LAST:event_BuscarActionPerformed

    //Eventos de validacion del JtextField.
    private void ID_jtextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ID_jtextFieldKeyTyped

        // llama al método que restringe los caracteres especiales.
        RestringirCaracteres(evt);
        if (ID_jtextField.getText().length() >= 10) {
            // si el rango se excede cuando se ingresa la identificación se muestra un mensaje y se desecha el dato de la tecla que presiono el usuario.
            JOptionPane.showMessageDialog(null, " Ha excedido el limite de numeros de la Identificacion", "ERROR", JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }


    }//GEN-LAST:event_ID_jtextFieldKeyTyped

    //Boton para volver al Menu principal
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //boton para volver al menu principal
        Menu_Principal ventana = new Menu_Principal();
        ventana.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_jButton1ActionPerformed

    //Boton para salir del programa
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //boton para cerrar la aplicacion
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    //Método que Restringe los caracteres especiales basado en su representación en código ASCII
    public void RestringirCaracteres(java.awt.event.KeyEvent caracter) {
        if (caracter.getKeyChar() >= 33 && caracter.getKeyChar() <= 47
                || caracter.getKeyChar() >= 58 && caracter.getKeyChar() <= 64
                || caracter.getKeyChar() >= 91 && caracter.getKeyChar() <= 96
                || caracter.getKeyChar() >= 123 && caracter.getKeyChar() <= 208
                || caracter.getKeyChar() >= 210 && caracter.getKeyChar() <= 240
                || caracter.getKeyChar() >= 242 && caracter.getKeyChar() <= 8482) {

            // si esta el rango establecido, entonces, se desecha el dato ingresado por el usuario y se muestra el mensaje del JPotionPane.
            caracter.consume();
            JOptionPane.showMessageDialog(null, "No se permiten caracteres especiales ");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Box_Tipo_Prestamo;
    private javax.swing.JButton Buscar;
    private javax.swing.JTextField ID_jtextField;
    private javax.swing.JPanel Panel_Listado;
    private javax.swing.JPanel Panel_Titulo;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
