package ventanas;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Minor
 */
public class Menu_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Principal
     */
    public Menu_Principal() {
        initComponents();
        //para darle nombre y centrar la ventana
        this.setTitle("Proyecto Final Minor Marin Obando");
        this.setLocationRelativeTo(null);
        //para darle color a los paneles
        this.Panel_Titulo.setBackground(new Color(246, 235, 241, 140));
        this.Panel_Transaccion.setBackground(new Color(246, 235, 241, 140));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Transaccion = new javax.swing.JPanel();
        jBox_Tipo_Transaccion = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Panel_Titulo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(390, 260));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Transaccion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBox_Tipo_Transaccion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBox_Tipo_Transaccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción..", "Agregar/Actualizar/Eliminar Clientes..", "Realizar Cotización..", "Mostrar Prestamos Aprobados.." }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Tipo de Transaccion");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Continuar>>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_TransaccionLayout = new javax.swing.GroupLayout(Panel_Transaccion);
        Panel_Transaccion.setLayout(Panel_TransaccionLayout);
        Panel_TransaccionLayout.setHorizontalGroup(
            Panel_TransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_TransaccionLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(Panel_TransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_TransaccionLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_TransaccionLayout.createSequentialGroup()
                        .addComponent(jBox_Tipo_Transaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
            .addGroup(Panel_TransaccionLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Panel_TransaccionLayout.setVerticalGroup(
            Panel_TransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_TransaccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBox_Tipo_Transaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(Panel_Transaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 330, 130));

        Panel_Titulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Sistema de Financiamiento");

        javax.swing.GroupLayout Panel_TituloLayout = new javax.swing.GroupLayout(Panel_Titulo);
        Panel_Titulo.setLayout(Panel_TituloLayout);
        Panel_TituloLayout.setHorizontalGroup(
            Panel_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_TituloLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel3)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        Panel_TituloLayout.setVerticalGroup(
            Panel_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_TituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(Panel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 330, 50));

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Menu2.png"))); // NOI18N
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Botón que determina que acción realizar con base a la selección del combobox
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        switch (jBox_Tipo_Transaccion.getSelectedIndex()) {
            case 0: // no ha seleccionado ninguna opción
                JOptionPane.showMessageDialog(null, " Debe Selecionar una opción ", "ERROR", JOptionPane.ERROR_MESSAGE);
                break;
            case 1: // muestra la ventana de datos cliente
                Datos_Clientes ventana = new Datos_Clientes();
                ventana.setVisible(true);
                this.dispose();

                break;
            case 2:  // muestra la ventana de cotizar
                Cotizar ventana2 = new Cotizar();
                ventana2.setVisible(true);
                this.dispose();

                break;
            case 3: // muestra la ventana del listado de los prestamos
                Listado_Prestamos ventana3 = new Listado_Prestamos();
                ventana3.setVisible(true);
                this.dispose();
                break;
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Titulo;
    private javax.swing.JPanel Panel_Transaccion;
    private javax.swing.JComboBox<String> jBox_Tipo_Transaccion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel menu;
    // End of variables declaration//GEN-END:variables
}
