
package Ventanas;
//Importación de las librerías utilizadas en esta ventana.
import java.awt.Color;

/**
 *
 * @author Minor
 */
public class Reporte extends javax.swing.JFrame {

    /** Creates new form Reporte */
    public Reporte() {
        initComponents();
        // Estas lineas le asigan un nombre a la ventana que se muestra y la centra en la pantalla.
        this.setTitle("Tarea 1 Minor Marin Obando");
        this.setLocationRelativeTo(null);
        //Esto le brinda a los JPanel el color deseado y la transparencia inmediatamente cuando se abre esta ventana.
        jPanel_Reporte_Titulo.setBackground(new Color(246,235,241,140));
        jPanel_Reporte.setBackground(new Color(246,235,241,140));
        jPanel_Reporte_Boton.setBackground(new Color(246,235,241,140));
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Reporte_Titulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel_Reporte = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel_Reporte_Nombre = new javax.swing.JLabel();
        jLabel_Reporte_Identificacion = new javax.swing.JLabel();
        jLabel_Reporte_Edad = new javax.swing.JLabel();
        jLabel_Reporte_Ingreso = new javax.swing.JLabel();
        jLabel_Reporte_Monto_Prestamo = new javax.swing.JLabel();
        jLabel_Reporte_Meses = new javax.swing.JLabel();
        jLabel_Reporte_Renta_Mensual = new javax.swing.JLabel();
        jLabel_Reporte_ID_Cotizacion = new javax.swing.JLabel();
        jLabel_Reporte_Fecha = new javax.swing.JLabel();
        jPanel_Reporte_Boton = new javax.swing.JPanel();
        jButton_Regresar = new javax.swing.JButton();
        FondoReporte = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Reporte_Titulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("REPORTE FINANCIAMIENTO");

        javax.swing.GroupLayout jPanel_Reporte_TituloLayout = new javax.swing.GroupLayout(jPanel_Reporte_Titulo);
        jPanel_Reporte_Titulo.setLayout(jPanel_Reporte_TituloLayout);
        jPanel_Reporte_TituloLayout.setHorizontalGroup(
            jPanel_Reporte_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Reporte_TituloLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel1)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel_Reporte_TituloLayout.setVerticalGroup(
            jPanel_Reporte_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Reporte_TituloLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_Reporte_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 480, 40));

        jPanel_Reporte.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("ID Cotización");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Fecha");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Nombre ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Identificación");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Edad");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Ingreso Mensual");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Monto Prestamo");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Meses a Cancelar");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Renta Mensual");

        jLabel_Reporte_Nombre.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel_Reporte_Nombre.setText("jLabel11");

        jLabel_Reporte_Identificacion.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel_Reporte_Identificacion.setText("jLabel12");

        jLabel_Reporte_Edad.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel_Reporte_Edad.setText("jLabel13");

        jLabel_Reporte_Ingreso.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel_Reporte_Ingreso.setText("jLabel14");

        jLabel_Reporte_Monto_Prestamo.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel_Reporte_Monto_Prestamo.setText("jLabel15");

        jLabel_Reporte_Meses.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel_Reporte_Meses.setText("jLabel16");

        jLabel_Reporte_Renta_Mensual.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel_Reporte_Renta_Mensual.setText("jLabel11");

        jLabel_Reporte_ID_Cotizacion.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel_Reporte_ID_Cotizacion.setText("jLabel11");

        jLabel_Reporte_Fecha.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel_Reporte_Fecha.setText("jLabel11");

        javax.swing.GroupLayout jPanel_ReporteLayout = new javax.swing.GroupLayout(jPanel_Reporte);
        jPanel_Reporte.setLayout(jPanel_ReporteLayout);
        jPanel_ReporteLayout.setHorizontalGroup(
            jPanel_ReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ReporteLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel_ReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ReporteLayout.createSequentialGroup()
                        .addGroup(jPanel_ReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_ReporteLayout.createSequentialGroup()
                        .addGroup(jPanel_ReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addGroup(jPanel_ReporteLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel2))
                            .addGroup(jPanel_ReporteLayout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addGroup(jPanel_ReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Reporte_Renta_Mensual, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel_ReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel_Reporte_Identificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                        .addComponent(jLabel_Reporte_Edad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel_Reporte_Ingreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel_Reporte_Monto_Prestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel_Reporte_Meses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel_ReporteLayout.createSequentialGroup()
                                        .addComponent(jLabel_Reporte_ID_Cotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel_Reporte_Fecha))
                                    .addComponent(jLabel_Reporte_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(21, 21, Short.MAX_VALUE))))
        );
        jPanel_ReporteLayout.setVerticalGroup(
            jPanel_ReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ReporteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_ReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel_Reporte_ID_Cotizacion)
                    .addComponent(jLabel_Reporte_Fecha))
                .addGap(34, 34, 34)
                .addGroup(jPanel_ReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel_Reporte_Nombre))
                .addGap(18, 18, 18)
                .addGroup(jPanel_ReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel_Reporte_Identificacion))
                .addGap(18, 18, 18)
                .addGroup(jPanel_ReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel_Reporte_Edad))
                .addGap(19, 19, 19)
                .addGroup(jPanel_ReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel_Reporte_Ingreso))
                .addGap(18, 18, 18)
                .addGroup(jPanel_ReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel_Reporte_Monto_Prestamo))
                .addGap(26, 26, 26)
                .addGroup(jPanel_ReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel_Reporte_Meses))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel_Reporte_Renta_Mensual)
                .addContainerGap())
        );

        getContentPane().add(jPanel_Reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 480, 340));

        jPanel_Reporte_Boton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton_Regresar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Regresar.setText("Regresar");
        jButton_Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Reporte_BotonLayout = new javax.swing.GroupLayout(jPanel_Reporte_Boton);
        jPanel_Reporte_Boton.setLayout(jPanel_Reporte_BotonLayout);
        jPanel_Reporte_BotonLayout.setHorizontalGroup(
            jPanel_Reporte_BotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Reporte_BotonLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jButton_Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel_Reporte_BotonLayout.setVerticalGroup(
            jPanel_Reporte_BotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Reporte_BotonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Regresar)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_Reporte_Boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 310, 60));

        FondoReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoReporte.png"))); // NOI18N
        getContentPane().add(FondoReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton_RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegresarActionPerformed
     // Estas líneas de código se encargan de cerrar esta ventana y mostrar la anterior cuando el usuario da click sobre el botón "Regresar".
     Solicitar_Datos Ventana_Ingresar_Datos = new Solicitar_Datos(); 
     Ventana_Ingresar_Datos.setVisible(true);
     this.dispose();
        
        
    }//GEN-LAST:event_jButton_RegresarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoReporte;
    private javax.swing.JButton jButton_Regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel jLabel_Reporte_Edad;
    public static javax.swing.JLabel jLabel_Reporte_Fecha;
    public static javax.swing.JLabel jLabel_Reporte_ID_Cotizacion;
    public static javax.swing.JLabel jLabel_Reporte_Identificacion;
    public static javax.swing.JLabel jLabel_Reporte_Ingreso;
    public static javax.swing.JLabel jLabel_Reporte_Meses;
    public static javax.swing.JLabel jLabel_Reporte_Monto_Prestamo;
    public static javax.swing.JLabel jLabel_Reporte_Nombre;
    public static javax.swing.JLabel jLabel_Reporte_Renta_Mensual;
    private javax.swing.JPanel jPanel_Reporte;
    private javax.swing.JPanel jPanel_Reporte_Boton;
    private javax.swing.JPanel jPanel_Reporte_Titulo;
    // End of variables declaration//GEN-END:variables

}
